// Shared data helpers — mirrors source/data.js, typed for Next.js.
// Use on the server (lib/supabase/server) or client (lib/supabase/client).
// Do not import `lib/i18n/dictionary` here — this module loads in many client chunks;
// pulling the full dict graph caused webpack runtime failures (undefined `.call`).

const R2 = (process.env.NEXT_PUBLIC_R2_PUBLIC_URL ?? '').replace(/\/$/, '')

/** In development, use Next rewrite (/r2-proxy → R2) so canvas + crossOrigin sees same-origin */
function r2DevProxyEnabled(): boolean {
  return process.env.NODE_ENV === 'development' && Boolean(R2)
}

export function r2PublicPath(pathWithinBucket: string): string {
  const enc = pathWithinBucket.split('/').map((s) => encodeURIComponent(s)).join('/')
  if (r2DevProxyEnabled()) return `/r2-proxy/${enc}`
  return `${R2}/${enc}`
}

/** Full URL for a stored image path — served from Cloudflare R2 (zero egress) */
export function imageUrl(file: string | null | undefined): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  return r2PublicPath(file)
}

/**
 * Thumbnail URL — points directly at thumbs/<base>.avif on R2.
 * Generated by sharp at upload time (400px AVIF). No optimizer needed.
 *
 * `size` param kept for API compatibility but ignored — all thumbs are 400px.
 */
export function thumbUrl(
  file: string | null | undefined,
  _size = 200,
): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  // Strip extension, always use .avif — matches backfill + new uploads
  const base = file.replace(/\.[^.]+$/, '')
  return r2PublicPath(`thumbs/${base}.avif`)
}

/** Extract 4-digit year from the Année date field */
export function yearOf(année: string | null | undefined): number | null {
  const y = parseInt(String(année ?? '').slice(0, 4))
  return Number.isFinite(y) && y > 1900 && y < 2100 ? y : null
}

export function decadeOf(year: number | null): string | null {
  if (!year) return null
  return `${Math.floor(year / 10) * 10}s`
}

// ── Status helpers ────────────────────────────────────────────

/** `Oeuvres.statusId` for OeuvreStatus label « Archive artiste » (PEM archive). */
export const STATUS_ID_ARCHIVE_ARTISTE = 3

/**
 * Status IDs that flip `Oeuvres.is_public = true` via the DB trigger
 * `sync_is_public_from_status()`. Mirror in code so we can predict the
 * trigger outcome (e.g. for visibility-gate event logging).
 *  2 Disponible · 4 Réservé · 6 Vendu · 7 Consigné · 8 Prêt · 11 Don
 */
export const STATUS_IDS_PUBLIC: readonly number[] = [2, 4, 6, 7, 8, 11]

/**
 * Canonical work state.
 *
 * Production states (derived from booleans when statusId resolves to en_production/available):
 *   en_production  — Catalogué=false  OR  Catalogué=true + NeedsPhotograph=true
 *   available      — Catalogué=true + NeedsPhotograph=false
 *
 * Ownership / flow states (from statusId → OeuvreStatus.label):
 *   reserved        — pending sale, manual assignment only
 *   consigned       — at gallery, no ownership transfer
 *   loan            — at institution, no ownership transfer
 *   sold            — ownership transferred
 *   gift            — ownership transferred, no payment
 *   artist_archive  — withdrawn from circulation (Pem retains)
 *   private_archive — withdrawn, private collection
 */
export type StatusKey =
  | 'en_production'
  | 'available'
  | 'reserved'
  | 'consigned'
  | 'loan'
  | 'sold'
  | 'gift'
  | 'artist_archive'
  | 'private_archive'

/** OeuvreStatus.label → StatusKey (FR + EN DB spellings; keep in sync with `OeuvreStatus`). */
const STATUS_LABEL_MAP: Record<string, StatusKey> = {
  'En production':   'en_production',
  'In production':   'en_production',
  'Disponible':      'available',
  'Available':       'available',
  'Réservé':         'reserved',
  'Reserved':        'reserved',
  'Archive artiste': 'artist_archive',
  'Artist archive':  'artist_archive',
  'Archive privée':  'private_archive',
  'Private archive': 'private_archive',
  'Vendu':           'sold',
  'Sold':            'sold',
  'Consigné':        'consigned',
  'Consigned':       'consigned',
  'Prêt':            'loan',
  'Loan':            'loan',
  'Borrowed':        'loan',
  'Gift':            'gift',
  'Don':             'gift',
}

export function statusKeyFromLabel(label: string | null | undefined): StatusKey {
  if (!label) return 'en_production'
  return STATUS_LABEL_MAP[label] ?? 'en_production'
}

/**
 * Resolve the StatusKey for a work.
 * Reads statusId against OeuvreStatus; explicit "En production" wins immediately.
 * For "Disponible" / missing row, refines with Catalogué + NeedsPhotograph (atelier gates).
 */
export function statusOf(
  o: any,
  statusLabelMap: Record<number, string> = {},
): StatusKey {
  let baseKey: StatusKey | null = null
  if (o.statusId !== null && o.statusId !== undefined) {
    const label = statusLabelMap[o.statusId]
    if (label) baseKey = statusKeyFromLabel(label)
  }

  // Explicit OeuvreStatus "En production" — honor it (drawer + list must match).
  if (baseKey === 'en_production') return 'en_production'

  // Sold, reserved, archived, consigned, loan, gift, …
  if (baseKey && baseKey !== 'available') return baseKey

  // statusId → Disponible (or unknown): refine with Catalogué / NeedsPhotograph so
  // "Disponible" + !Catalogué still reads as en_production.
  if (!o.Catalogué) return 'en_production'
  if (o.NeedsPhotograph || o.needsphotograph) return 'en_production'

  return 'available'
}

/** Commercial status from `Oeuvres.statusId` only — no Catalogué / NeedsPhotograph refinement. */
export function commercialStatusKeyFromRow(
  o: { statusId?: number | null },
  statusLabelMap: Record<number, string> = {},
): StatusKey {
  if (o.statusId === null || o.statusId === undefined) return 'en_production'
  const label = statusLabelMap[o.statusId]
  if (label) return statusKeyFromLabel(label)
  return 'en_production'
}

/** OeuvreStatus.id used by WorkDrawer pipeline segments (matches STATUS_STAGES ids). */
export function statusKeyToOeuvreStatusId(key: StatusKey): number {
  switch (key) {
    case 'en_production': return 1
    case 'available': return 2
    case 'reserved': return 4
    case 'consigned': return 7
    case 'loan': return 8
    case 'sold': return 6
    case 'gift': return 11
    case 'artist_archive': return STATUS_ID_ARCHIVE_ARTISTE
    case 'private_archive': return 5
    default: return 1
  }
}

/**
 * Which pipeline segment should appear selected: follows `statusOf` when the form matches saved row,
 * else the user's pending `statusId` while editing.
 */
export function pipelineHighlightStatusId(
  o: { statusId?: number | null; Catalogué?: boolean; NeedsPhotograph?: boolean; needsphotograph?: boolean },
  statusLabelMap: Record<number, string>,
  localStatusIdStr: string,
): number {
  if (String(o.statusId ?? '') !== localStatusIdStr && localStatusIdStr !== '') {
    const n = Number(localStatusIdStr)
    if (Number.isFinite(n) && n > 0) return n
  }
  return statusKeyToOeuvreStatusId(statusOf(o, statusLabelMap))
}

/** DB says « Disponible » but gates keep effective state in production (catalogue / photo). */
export function isAvailabilityRefinedToProduction(
  o: { statusId?: number | null; Catalogué?: boolean; NeedsPhotograph?: boolean; needsphotograph?: boolean },
  statusLabelMap: Record<number, string>,
): boolean {
  return (
    statusOf(o, statusLabelMap) === 'en_production' &&
    commercialStatusKeyFromRow(o, statusLabelMap) === 'available'
  )
}

/** Saved commercial segment id (from `Oeuvres.statusId`) — ignores catalogue/photo refinement. */
export function commercialPipelineSegmentId(
  o: { statusId?: number | null },
  statusLabelMap: Record<number, string>,
): number {
  const k = commercialStatusKeyFromRow(o, statusLabelMap)
  return statusKeyToOeuvreStatusId(k)
}

/** Effective segment after refinement (gates) — mirrors `statusOf` bar mapping. */
export function effectivePipelineSegmentId(
  o: { statusId?: number | null; Catalogué?: boolean; NeedsPhotograph?: boolean; needsphotograph?: boolean },
  statusLabelMap: Record<number, string>,
): number {
  return statusKeyToOeuvreStatusId(statusOf(o, statusLabelMap))
}

/**
 * Show both markers on the drawer bar when saved commercial step ≠ effective refined step while the form matches DB.
 */
export function statusDrawerShowCommercialEffectiveSplit(
  o: { statusId?: number | null; Catalogué?: boolean; NeedsPhotograph?: boolean; needsphotograph?: boolean },
  statusLabelMap: Record<number, string>,
  localStatusIdStr: string,
): boolean {
  if (String(o.statusId ?? '') !== localStatusIdStr || localStatusIdStr === '') return false
  return commercialPipelineSegmentId(o, statusLabelMap) !== effectivePipelineSegmentId(o, statusLabelMap)
}

/** Color for a StatusKey — used for row/grid tinting in Inventory */
export function statusColor(key: StatusKey): string {
  switch (key) {
    case 'en_production':   return 'var(--rust)'
    case 'available':       return 'var(--sage)'
    case 'reserved':        return 'var(--dust)'
    case 'consigned':       return 'var(--dust)'
    case 'loan':            return 'var(--cyan)'
    case 'sold':            return 'transparent'
    case 'gift':            return 'transparent'
    case 'artist_archive':  return 'var(--mt)'
    case 'private_archive': return 'var(--mt)'
    default:                return 'var(--tx3)'
  }
}

// ── Stage production color (kept for constellation/sort, not for chips) ──────

export type StageKey = 'idea' | 'wip' | 'drying' | 'mounting' | 'framing' | 'shot' | 'catalogued'

/** Returns a CSS color var string for a legacy StageProduction value */
export function stageColor(stage: string | null | undefined): string {
  switch (stage) {
    case 'idea':       return 'var(--ac)'
    case 'sketch':     return 'var(--rust)'
    case 'wip':        return 'var(--rust)'
    case 'drying':     return 'var(--dust)'
    case 'mounting':   return 'var(--dust)'
    case 'framing':    return 'var(--dust)'
    case 'shot':       return 'var(--cyan)'
    case 'catalogued': return 'var(--sage)'
    default:           return 'var(--tx3)'
  }
}

// ── Image filename helpers ────────────────────────────────────

/**
 * Parse the sequence number from an existing filename.
 * Returns 1 (first slot) if filename is null or unparseable.
 */
export function seqFromFilename(filename: string | null | undefined): number {
  if (!filename) return 1
  const m = filename.match(/^W_\d+_(\d+)_/)
  return m ? parseInt(m[1], 10) : 1
}

// ── Production stage helpers (legacy — kept for constellation/sort) ───────────

export type StageProductionKey =
  | 'stage_idea' | 'stage_sketch' | 'stage_wip'
  | 'stage_drying' | 'stage_framing' | 'stage_shot' | 'stage_catalogued'

export const STAGES: StageProductionKey[] = [
  'stage_idea', 'stage_sketch', 'stage_wip',
  'stage_drying', 'stage_framing', 'stage_shot', 'stage_catalogued',
]

/**
 * Infer a legacy production stage from DB fields.
 * Used only for constellation layout and sort — not for UI chips.
 */
export function stageOf(
  o: { Catalogué?: boolean | null; txtImageNameLink?: string | null; Encadree?: boolean | null; statusId?: number | null; NeedsPhotograph?: boolean | null },
  _statusLabelMap: Record<number, string> = {},
): StageProductionKey {
  if (o.NeedsPhotograph) return 'stage_shot'
  if (o.Catalogué) return 'stage_catalogued'
  if (o.txtImageNameLink) return 'stage_shot'
  if (o.Encadree) return 'stage_framing'
  return 'stage_wip'
}

// ── Dimensions: circular supports (diameter U+2300) ────────────────

/** Diameter sign ⌀ (Unicode U+2300) */
export const DIAMETER_SIGN = '\u2300'

/** True when support label indicates a round/circular support (e.g. papier rond). */
export function isCircularSupport(supportLabel: string | null | undefined): boolean {
  if (!supportLabel?.trim()) return false
  const n = supportLabel.toLowerCase().normalize('NFD').replace(/\p{M}/gu, '')
  return /\b(rond|circular|round|circulaire|disque)\b/.test(n) || /\bpapier\s*rond\b/.test(n)
}

/** Compact dims for lists: `H×L` or `⌀d` if diameter was stored only in Profondeur. */
export function formatInventoryDims(
  h: string | null | undefined,
  l: string | null | undefined,
  supportLabel: string | null | undefined,
  profondeur?: string | null | undefined,
): string {
  const ht = (h ?? '').trim()
  const lt = (l ?? '').trim()
  const pt = (profondeur ?? '').trim()

  if (isCircularSupport(supportLabel)) {
    if (ht && lt && ht === lt) return `${DIAMETER_SIGN}${ht}`
    if (ht && !lt) return `${DIAMETER_SIGN}${ht}`
    if (!ht && lt) return `${DIAMETER_SIGN}${lt}`
    if (!ht && !lt && pt) return `${DIAMETER_SIGN}${pt}`
    if (ht && lt) return `${ht}×${lt}`
    return '—'
  }
  if (ht && lt) return `${ht}×${lt}`
  return '—'
}

// ── Constellation coordinate helpers ─────────────────────────

/**
 * Compute deterministic SVG x/y for a work given the year range
 * and the ordered list of technique IDs.
 */
export function constellationCoords(
  year: number,
  techniqueId: number,
  techniqueOrder: number[],
  minYear: number,
  xScale = 60,
  rowHeight = 48,
): { x: number; y: number } {
  const x = (year - minYear) * xScale
  const y = techniqueOrder.indexOf(techniqueId) * rowHeight
  return { x: Math.max(0, x), y: Math.max(0, y) }
}

/** Deterministic node color from technique ID */
export function techniqueColor(techniqueId: number): string {
  const hue = (techniqueId * 47) % 360
  return `hsl(${hue}, 40%, 55%)`
}

/** Types of suivi_process that are allowed to have an exhibition layout/floorplan */
export const EXHIBITION_READY_TYPES = [
  'salon',
  'exposition',
  'consignment',
  'evenement',
  'collaboration',
  'prix',
  'residence',
]
