// Shared data helpers — mirrors source/data.js, typed for Next.js.
// Use on the server (lib/supabase/server) or client (lib/supabase/client).

const R2 = process.env.NEXT_PUBLIC_R2_PUBLIC_URL ?? ''

/** Full URL for a stored image path — served from Cloudflare R2 (zero egress) */
export function imageUrl(file: string | null | undefined): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  return `${R2}/${encodeURIComponent(file)}`
}

/**
 * Thumbnail URL — points directly at thumbs/<base>.avif on R2.
 * Generated by sharp at upload time (400px AVIF). No optimizer needed.
 *
 * `size` param kept for API compatibility but ignored — all thumbs are 400px.
 */
export function thumbUrl(
  file: string | null | undefined,
  _size = 200,
): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  // Strip extension, always use .avif — matches backfill + new uploads
  const base = file.replace(/\.[^.]+$/, '')
  return `${R2}/thumbs/${encodeURIComponent(base)}.avif`
}

/** Extract 4-digit year from the Année date field */
export function yearOf(année: string | null | undefined): number | null {
  const y = parseInt(String(année ?? '').slice(0, 4))
  return Number.isFinite(y) && y > 1900 && y < 2100 ? y : null
}

export function decadeOf(year: number | null): string | null {
  if (!year) return null
  return `${Math.floor(year / 10) * 10}s`
}

// ── Stage production color ─────────────────────────────────────

export type StageKey = 'idea' | 'wip' | 'drying' | 'framing' | 'shot' | 'catalogued'

/** Returns a CSS color var string for a StageProduction value */
export function stageColor(stage: string | null | undefined): string {
  switch (stage) {
    case 'idea':      return 'var(--ac)'
    case 'wip':       return 'var(--rust)'
    case 'drying':    return 'var(--dust)'
    case 'mounting':  return 'var(--dust)'
    case 'framing':   return 'var(--dust)'
    case 'shot':      return 'var(--cyan)'
    case 'catalogued':return 'var(--sage)'
    default:          return 'transparent'
  }
}

// ── Status helpers ────────────────────────────────────────────

export type StatusKey =
  | 'studio' | 'consigned' | 'sold' | 'loan' | 'wip' | 'destroyed' | 'lost' | 'gift'

/** Map OeuvreStatus.label → our canonical key */
const STATUS_LABEL_MAP: Record<string, StatusKey> = {
  WIP:        'wip',
  Available:  'studio',
  Private:    'studio',
  Reserved:   'studio',
  Borrowed:   'loan',
  Sold:       'sold',
  Consigned:  'consigned',
  Loan:       'loan',
  Destroyed:  'destroyed',
  Lost:       'lost',
  Gift:       'gift',
}

export function statusKeyFromLabel(label: string | null | undefined): StatusKey {
  if (!label) return 'studio'
  return STATUS_LABEL_MAP[label] ?? 'studio'
}

/**
 * Resolve the StatusKey for a work.
 * Checks statusId against the OeuvreStatus table first, falls back to hash.
 */
export function statusOf(
  o: { statusId: number | null; OeuvreID: number },
  statusLabelMap: Record<number, string>,
): StatusKey {
  if (o.statusId !== null) {
    const label = statusLabelMap[o.statusId]
    if (label) return statusKeyFromLabel(label)
  }
  return fallbackStatus(o.OeuvreID)
}

/** Deterministic fallback when statusId is null (matches prototype heuristic) */
const STATUSES: StatusKey[] = [
  'studio', 'studio', 'studio', 'studio',
  'consigned', 'consigned', 'sold', 'loan', 'wip',
]

export function hashId(id: number): number {
  return Math.abs((id * 2654435761) % 2147483647)
}

export function fallbackStatus(oeuvreId: number): StatusKey {
  return STATUSES[hashId(oeuvreId) % STATUSES.length]
}

// ── Image filename helpers ────────────────────────────────────

/**
 * Build a canonical storage filename for a work image.
 * Pattern: W_{oid}_{seq:02}_{sanitized}.{ext}
 * Example: W_2338_01_portrait_final.jpg
 */
export function makeFilename(oid: number, seq: number, originalName: string): string {
  const seqStr     = String(seq).padStart(2, '0')
  const extMatch   = originalName.match(/\.([^.]+)$/)
  const ext        = extMatch ? extMatch[1].toLowerCase() : 'jpg'
  const sanitized  = originalName
    .replace(/\.[^.]+$/, '')          // strip extension
    .replace(/[^a-zA-Z0-9_-]/g, '_') // replace special chars
    .replace(/_+/g, '_')              // collapse runs
    .replace(/^_|_$/g, '')            // trim edge underscores
    .slice(0, 60)
  return `W_${oid}_${seqStr}_${sanitized}.${ext}`
}

/**
 * Parse the sequence number from an existing filename.
 * Returns 1 (first slot) if filename is null or unparseable.
 */
export function seqFromFilename(filename: string | null | undefined): number {
  if (!filename) return 1
  const m = filename.match(/^W_\d+_(\d+)_/)
  return m ? parseInt(m[1], 10) : 1
}

// ── Production stage helpers ──────────────────────────────────

export type StageKey =
  | 'stage_idea' | 'stage_sketch' | 'stage_wip'
  | 'stage_drying' | 'stage_framing' | 'stage_shot' | 'stage_catalogued'

export const STAGES: StageKey[] = [
  'stage_idea', 'stage_sketch', 'stage_wip',
  'stage_drying', 'stage_framing', 'stage_shot', 'stage_catalogued',
]

/**
 * Infer the production stage of a work from real DB fields.
 * Priority: Catalogué > has image > framed > WIP status > hash fallback.
 */
export function stageOf(
  o: { Catalogué?: boolean | null; txtImageNameLink?: string | null; Encadree?: boolean | null; statusId?: number | null },
  statusLabelMap: Record<number, string> = {},
): StageKey {
  if (o.Catalogué) return 'stage_catalogued'
  if (o.txtImageNameLink) return 'stage_shot'
  if (o.Encadree) return 'stage_framing'
  if (o.statusId !== null && o.statusId !== undefined) {
    const label = statusLabelMap[o.statusId]
    if (label === 'WIP') return 'stage_wip'
  }
  // Deterministic fallback over the early stages (idea / sketch / drying)
  const h = hashId(
    typeof (o as { OeuvreID?: number }).OeuvreID === 'number'
      ? (o as { OeuvreID: number }).OeuvreID
      : 0,
  )
  const earlyStages: StageKey[] = ['stage_idea', 'stage_sketch', 'stage_drying']
  return earlyStages[h % earlyStages.length]
}

// ── Constellation coordinate helpers ─────────────────────────

/**
 * Compute deterministic SVG x/y for a work given the year range
 * and the ordered list of technique IDs.
 *
 * x = (year - minYear) * xScale
 * y = techniqueIndex * rowHeight
 */
export function constellationCoords(
  year: number,
  techniqueId: number,
  techniqueOrder: number[],
  minYear: number,
  xScale = 60,
  rowHeight = 48,
): { x: number; y: number } {
  const x = (year - minYear) * xScale
  const y = techniqueOrder.indexOf(techniqueId) * rowHeight
  return { x: Math.max(0, x), y: Math.max(0, y) }
}

/** Deterministic node color from technique ID */
export function techniqueColor(techniqueId: number): string {
  const hue = (techniqueId * 47) % 360
  return `hsl(${hue}, 40%, 55%)`
}
