// Shared data helpers — mirrors source/data.js, typed for Next.js.
// Use on the server (lib/supabase/server) or client (lib/supabase/client).

const R2 = process.env.NEXT_PUBLIC_R2_PUBLIC_URL ?? ''

/** Full URL for a stored image path — served from Cloudflare R2 (zero egress) */
export function imageUrl(file: string | null | undefined): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  return `${R2}/${encodeURIComponent(file)}`
}

/**
 * Thumbnail URL — points directly at thumbs/<base>.avif on R2.
 * Generated by sharp at upload time (400px AVIF). No optimizer needed.
 *
 * `size` param kept for API compatibility but ignored — all thumbs are 400px.
 */
export function thumbUrl(
  file: string | null | undefined,
  _size = 200,
): string | null {
  if (!file) return null
  if (file.startsWith('http')) return file
  // Strip extension, always use .avif — matches backfill + new uploads
  const base = file.replace(/\.[^.]+$/, '')
  return `${R2}/thumbs/${encodeURIComponent(base)}.avif`
}

/** Extract 4-digit year from the Année date field */
export function yearOf(année: string | null | undefined): number | null {
  const y = parseInt(String(année ?? '').slice(0, 4))
  return Number.isFinite(y) && y > 1900 && y < 2100 ? y : null
}

export function decadeOf(year: number | null): string | null {
  if (!year) return null
  return `${Math.floor(year / 10) * 10}s`
}

// ── Status helpers ────────────────────────────────────────────

/**
 * Canonical work state.
 *
 * Production states (derived from booleans when statusId resolves to en_production/available):
 *   en_production  — Catalogué=false  OR  Catalogué=true + NeedsPhotograph=true
 *   available      — Catalogué=true + NeedsPhotograph=false
 *
 * Ownership / flow states (from statusId → OeuvreStatus.label):
 *   reserved        — pending sale, manual assignment only
 *   consigned       — at gallery, no ownership transfer
 *   loan            — at institution, no ownership transfer
 *   sold            — ownership transferred
 *   gift            — ownership transferred, no payment
 *   artist_archive  — withdrawn from circulation (Pem retains)
 *   private_archive — withdrawn, private collection
 */
export type StatusKey =
  | 'en_production'
  | 'available'
  | 'reserved'
  | 'consigned'
  | 'loan'
  | 'sold'
  | 'gift'
  | 'artist_archive'
  | 'private_archive'

/** Map OeuvreStatus.label → canonical StatusKey */
const STATUS_LABEL_MAP: Record<string, StatusKey> = {
  'En production':   'en_production',
  'Disponible':      'available',
  'Réservé':         'reserved',
  'Archive artiste': 'artist_archive',
  'Archive privée':  'private_archive',
  'Vendu':           'sold',
  'Sold':            'sold',
  'Consigné':        'consigned',
  'Consigned':       'consigned',
  'Prêt':            'loan',
  'Loan':            'loan',
  'Borrowed':        'loan',
  'Gift':            'gift',
  'Don':             'gift',
}

export function statusKeyFromLabel(label: string | null | undefined): StatusKey {
  if (!label) return 'en_production'
  return STATUS_LABEL_MAP[label] ?? 'en_production'
}

/**
 * Resolve the StatusKey for a work.
 * Reads statusId against OeuvreStatus first.
 * Falls back to deriving from Catalogué + NeedsPhotograph booleans.
 */
export function statusOf(
  o: any,
  statusLabelMap: Record<number, string> = {},
): StatusKey {
  if (o.statusId !== null && o.statusId !== undefined) {
    const label = statusLabelMap[o.statusId]
    if (label) return statusKeyFromLabel(label)
  }
  // Boolean fallback when statusId is missing or unmapped
  if (!o.Catalogué) return 'en_production'
  if (o.NeedsPhotograph) return 'en_production'
  return 'available'
}

/** Color for a StatusKey — used for row/grid tinting in InventoryTab */
export function statusColor(key: StatusKey): string {
  switch (key) {
    case 'en_production':   return 'var(--rust)'
    case 'available':       return 'var(--sage)'
    case 'reserved':        return 'var(--dust)'
    case 'consigned':       return 'var(--dust)'
    case 'loan':            return 'var(--cyan)'
    case 'sold':            return 'transparent'
    case 'gift':            return 'transparent'
    case 'artist_archive':  return 'var(--mt)'
    case 'private_archive': return 'var(--mt)'
    default:                return 'var(--tx3)'
  }
}

// ── Stage production color (kept for constellation/sort, not for chips) ──────

export type StageKey = 'idea' | 'wip' | 'drying' | 'mounting' | 'framing' | 'shot' | 'catalogued'

/** Returns a CSS color var string for a legacy StageProduction value */
export function stageColor(stage: string | null | undefined): string {
  switch (stage) {
    case 'idea':       return 'var(--ac)'
    case 'sketch':     return 'var(--rust)'
    case 'wip':        return 'var(--rust)'
    case 'drying':     return 'var(--dust)'
    case 'mounting':   return 'var(--dust)'
    case 'framing':    return 'var(--dust)'
    case 'shot':       return 'var(--cyan)'
    case 'catalogued': return 'var(--sage)'
    default:           return 'var(--tx3)'
  }
}

// ── Image filename helpers ────────────────────────────────────

/**
 * Build a canonical storage filename for a work image.
 * Pattern: W_{oid}_{seq:02}_{sanitized}.{ext}
 * Example: W_2338_01_portrait_final.jpg
 */
export function makeFilename(oid: number, seq: number, originalName: string): string {
  const seqStr     = String(seq).padStart(2, '0')
  const extMatch   = originalName.match(/\.([^.]+)$/)
  const ext        = extMatch ? extMatch[1].toLowerCase() : 'jpg'
  const sanitized  = originalName
    .replace(/\.[^.]+$/, '')          // strip extension
    .replace(/[^a-zA-Z0-9_-]/g, '_') // replace special chars
    .replace(/_+/g, '_')              // collapse runs
    .replace(/^_|_$/g, '')            // trim edge underscores
    .slice(0, 60)
  return `W_${oid}_${seqStr}_${sanitized}.${ext}`
}

/**
 * Parse the sequence number from an existing filename.
 * Returns 1 (first slot) if filename is null or unparseable.
 */
export function seqFromFilename(filename: string | null | undefined): number {
  if (!filename) return 1
  const m = filename.match(/^W_\d+_(\d+)_/)
  return m ? parseInt(m[1], 10) : 1
}

// ── Production stage helpers (legacy — kept for constellation/sort) ───────────

export type StageProductionKey =
  | 'stage_idea' | 'stage_sketch' | 'stage_wip'
  | 'stage_drying' | 'stage_framing' | 'stage_shot' | 'stage_catalogued'

export const STAGES: StageProductionKey[] = [
  'stage_idea', 'stage_sketch', 'stage_wip',
  'stage_drying', 'stage_framing', 'stage_shot', 'stage_catalogued',
]

/**
 * Infer a legacy production stage from DB fields.
 * Used only for constellation layout and sort — not for UI chips.
 */
export function stageOf(
  o: { Catalogué?: boolean | null; txtImageNameLink?: string | null; Encadree?: boolean | null; statusId?: number | null; NeedsPhotograph?: boolean | null },
  _statusLabelMap: Record<number, string> = {},
): StageProductionKey {
  if (o.NeedsPhotograph) return 'stage_shot'
  if (o.Catalogué) return 'stage_catalogued'
  if (o.txtImageNameLink) return 'stage_shot'
  if (o.Encadree) return 'stage_framing'
  return 'stage_wip'
}

// ── Constellation coordinate helpers ─────────────────────────

/**
 * Compute deterministic SVG x/y for a work given the year range
 * and the ordered list of technique IDs.
 */
export function constellationCoords(
  year: number,
  techniqueId: number,
  techniqueOrder: number[],
  minYear: number,
  xScale = 60,
  rowHeight = 48,
): { x: number; y: number } {
  const x = (year - minYear) * xScale
  const y = techniqueOrder.indexOf(techniqueId) * rowHeight
  return { x: Math.max(0, x), y: Math.max(0, y) }
}

/** Deterministic node color from technique ID */
export function techniqueColor(techniqueId: number): string {
  const hue = (techniqueId * 47) % 360
  return `hsl(${hue}, 40%, 55%)`
}

/** Types of suivi_process that are allowed to have an exhibition layout/floorplan */
export const EXHIBITION_READY_TYPES = [
  'salon',
  'exposition',
  'consignment',
  'evenement',
  'collaboration',
  'prix',
  'residence',
]
