
import { createClient } from '@supabase/supabase-js'
import fs from 'fs'

async function run() {
  const env = fs.readFileSync('.env.local', 'utf8').split('\n').reduce((acc: any, line) => {
    const [k, ...v] = line.split('=')
    if (k && v) acc[k] = v.join('=').trim()
    return acc
  }, {})

  const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY)

  const sql = `
  CREATE TABLE IF NOT EXISTS contact_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER REFERENCES "Contact"("ContactID") ON DELETE CASCADE,
    email TEXT NOT NULL,
    label TEXT,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS contact_phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER REFERENCES "Contact"("ContactID") ON DELETE CASCADE,
    country_code TEXT,
    phone TEXT NOT NULL,
    label TEXT,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS contact_websites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER REFERENCES "Contact"("ContactID") ON DELETE CASCADE,
    url TEXT NOT NULL,
    label TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS contact_socials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER REFERENCES "Contact"("ContactID") ON DELETE CASCADE,
    platform TEXT NOT NULL,
    handle TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  DO $$ 
  BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='contact_addresses' AND column_name='shipping_notes') THEN
      ALTER TABLE contact_addresses ADD COLUMN shipping_notes TEXT;
    END IF;
  END $$;
  `

  console.log('Executing SQL...')
  const { error } = await sb.rpc('exec_sql', { sql })
  if (error) {
    console.error('Error:', error)
  } else {
    console.log('Success!')
  }
}

run()
